baseURL = "https://bellowaverage.github.io/"
languageCode = "en-us"
title = "Chris Wang Personal Showcase"
theme = "hugo-digital-garden-theme"
themesdir = "./themes"
copyright = "Chris Wang ©"


[params]
  name = "Chris Wang"
  description = "This site documents my work & technical notes starting from 2020."
  initials = "CW"
  googleAnalytics = ""

  [[params.social]]
    name = "Github"
    link = "https://github.com/BellowAverage"
    icon = "fab fa-github"

  [[params.social]]
    name = "LinkedIn"
    link = "https://www.linkedin.com/in/chris-wang-a4b1a9216/"
    icon = "fab fa-linkedin-in"


[menu]
  [[menu.main]]
    name = "Quick Access"
    url = "/quickaccess/"
    weight = 1
  [[menu.main]]
    name = "Notes & Blogs"
    url = "/notes/"
    weight = 2
  [[menu.main]]
    name = "Featured Articles"
    url = "/featuredarticles/"
    weight = 3
  [[menu.main]]
    name = "Site Documentation"
    url = "/about/"
    weight = 4


[taxonomies]
  garden_tags = 'garden_tags'
  project_tags = 'project_tags'
  library_tags = 'library_tags'


[markup]
  defaultMarkdownHandler = 'goldmark'
  [markup.goldmark.renderer]
    unsafe = true
  [markup.goldmark.parser]
    autoHeadingID = true
    autoHeadingIDType = 'github'
    wrapStandAloneImageWithinParagraph = true
    [markup.goldmark.parser.attribute]
      block = false
      title = true
  [markup.goldmark.extensions]
    definitionList = true
    footnote = true
    linkify = true
    strikethrough = true
    table = true
    taskList = true
    typographer = true
  [markup.highlight]
    # Choose from https://xyproto.github.io/splash/docs/all.html
    style = 'monokailight'